### PR TITLE
Create a Java code sample for public use

### PR DESCRIPTION
**Pull request by TheCricket**
I think code samples is a great idea and I feel that more support will only increase the benefits from it. This is a simple bot that will connect and reply to custom commands from the user. It is a good boilerplate for a quick project but still allows a solid framework for customization and advancement.

### CODE REVIEW

**Comment by travistyoj** [comment]
Hey, thanks so much for adding this so quickly!  One of the design tenants I'd like to encourage with our code samples is showing how to use libraries when they are available.  I noticed this chatbot reads and writes to raw sockets.  What do you think about updating to use a popular IRC library?  It should allow a more extensible base for developers that use it.

**Comment by TheCricket** [comment]
Do you have any suggestions? or free reign go ahead

**Comment by travistyoj** [comment]
Looks great! Just to let you know, this will have to go through an internal review process, but I'm including it in our upcoming May drop with new samples.  Thank you!

**Comment by TheCricket** [comment]
Awesome!

**Comment by TheCricket** [comment]
Thanks guys!

**Pull request merged**
